// ============================================================================
// Paax — Custom Offline-First Service Worker
// ============================================================================
// This service worker enforces a CACHE-FIRST strategy for the app shell so
// that the Flutter UI loads instantly on cold start, even without a network
// connection (critical for Android TWA offline behaviour).
//
// Flutter's own `flutter_service_worker.js` is still generated by the build
// and handles versioned caching of compiled assets, but this worker sits in
// front of it and guarantees that the core shell is always available.
// ============================================================================

const CACHE_NAME = 'paax-app-shell-v1';

// Core app-shell resources that MUST be cached on install.
// After `flutter build web`, these files exist at the root of `build/web/`.
const APP_SHELL_URLS = [
  './',                       // index.html (via navigation)
  './index.html',
  './manifest.json',
  './flutter.js',
  './flutter_bootstrap.js',
  './main.dart.js',
  './favicon.png',
  './icons/Icon-192.png',
  './icons/Icon-512.png',
  './icons/Icon-maskable-192.png',
  './icons/Icon-maskable-512.png',
];

// Patterns that should ALWAYS be served cache-first.
// Matches: the app shell list above, plus any CanvasKit / font / asset files
// produced by the Flutter build.
const CACHE_FIRST_PATTERNS = [
  /\/(index\.html)?$/,                 // navigation requests to the shell
  /\/main\.dart\.js/,
  /\/flutter\.js/,
  /\/flutter_bootstrap\.js/,
  /\/manifest\.json/,
  /\/favicon\.png/,
  /\/icons\//,
  /\/assets\//,                         // Flutter asset bundle (fonts, images)
  /\/canvaskit\//,                      // CanvasKit WASM/JS
  /\.js$/, // all JS chunks (deferred loading)
];

// ---------------------------------------------------------------------------
// INSTALL — pre-cache the app shell
// ---------------------------------------------------------------------------
self.addEventListener('install', (event) => {
  // Skip waiting so the new SW activates immediately.
  self.skipWaiting();

  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[SW] Pre-caching app shell');
      return cache.addAll(APP_SHELL_URLS).catch((err) => {
        // Non-fatal: some URLs may not exist yet (e.g. flutter_bootstrap.js
        // is only generated in newer Flutter versions). Cache what we can.
        console.warn('[SW] Some app-shell URLs could not be cached:', err);
        // Fall back to adding individually so one failure doesn't block all.
        return Promise.allSettled(
          APP_SHELL_URLS.map((url) => cache.add(url).catch(() => {}))
        );
      });
    })
  );
});

// ---------------------------------------------------------------------------
// ACTIVATE — claim all clients + clean old caches
// ---------------------------------------------------------------------------
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      )
    ).then(() => self.clients.claim())
  );
});

// ---------------------------------------------------------------------------
// FETCH — cache-first for app shell, stale-while-revalidate for the rest
// ---------------------------------------------------------------------------
self.addEventListener('fetch', (event) => {
  const request = event.request;

  // Only handle GET requests.
  if (request.method !== 'GET') return;

  // For navigation requests (HTML pages), ALWAYS serve the cached index.html
  // (single-page app). This is the key to preventing the TWA's offline
  // fallback screen from appearing.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('./index.html').then((cached) => {
        if (cached) return cached;
        return fetch(request).then((response) => {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((c) => c.put('./index.html', clone));
          return response;
        });
      })
    );
    return;
  }

  // Check if this URL matches a cache-first pattern.
  const url = new URL(request.url);
  const isCacheFirst = CACHE_FIRST_PATTERNS.some((p) => p.test(url.pathname));

  if (isCacheFirst) {
    // Cache-first: serve from cache immediately, update cache in background.
    event.respondWith(
      caches.match(request).then((cached) => {
        // Background revalidation — keep the cache fresh for next visit.
        const networkFetch = fetch(request)
          .then((response) => {
            if (response && response.ok) {
              const clone = response.clone();
              caches.open(CACHE_NAME).then((c) => c.put(request, clone));
            }
            return response;
          })
          .catch(() => cached); // network failed, cache is the only option

        return cached || networkFetch;
      })
    );
    return;
  }

  // Everything else (API calls, dynamic content): network-first.
  // We don't cache these — they'll naturally fail offline, which is expected.
});
